//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CusPermissions = new HashSet<CusPermission>();
        }
    
        public int Cus_Id { get; set; }
        public string Cus_Name { get; set; }
        public Nullable<int> Cus_phone { get; set; }
        public Nullable<int> cus_Mobile { get; set; }
        public Nullable<int> Cus_Fax { get; set; }
        public string Cus_Email { get; set; }
        public string cus_Website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CusPermission> CusPermissions { get; set; }
    }
}
