//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_Movement
    {
        public int id { get; set; }
        public string Warhouse_from { get; set; }
        public string Warhouse_To { get; set; }
        public string productname { get; set; }
        public Nullable<int> transferQuntity { get; set; }
        public string supplier { get; set; }
        public Nullable<System.DateTime> productiondate { get; set; }
        public Nullable<System.DateTime> dateoftransfer { get; set; }
    }
}
