//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int Unit_Id { get; set; }
        public string Unit1 { get; set; }
        public Nullable<int> prod_Id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
